"""Added House Table

Revision ID: 3163378c5057
Revises: 3837ea740f9f
Create Date: 2022-06-16 17:41:28.964582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3163378c5057'
down_revision = '3837ea740f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=25), nullable=False),
    sa.Column('locality', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('house_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house')
    # ### end Alembic commands ###
