"""added img in house model

Revision ID: 6a3fc2949560
Revises: 0248d1e420cc
Create Date: 2022-06-22 10:26:46.923435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3fc2949560'
down_revision = '0248d1e420cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('size', sa.String(length=20), nullable=False))
    op.add_column('house', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.drop_column('house', 'size_sqft')
    op.drop_column('user', 'user_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_image', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('house', sa.Column('size_sqft', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('house', 'image_file')
    op.drop_column('house', 'size')
    # ### end Alembic commands ###
