"""initial migration

Revision ID: 6f29a00d7e88
Revises: 
Create Date: 2022-06-15 19:04:53.633907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f29a00d7e88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('user_image', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_image')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
