"""Updated House Table

Revision ID: 75626b374cb9
Revises: 8e819147a7ef
Create Date: 2022-06-20 12:08:21.428360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75626b374cb9'
down_revision = '8e819147a7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('size_sqft', sa.String(length=20), nullable=False))
    op.add_column('house', sa.Column('rent_per_month', sa.String(length=20), nullable=True))
    op.add_column('house', sa.Column('verified', sa.String(), nullable=False))
    op.alter_column('house', 'price',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('house', 'deposit')
    op.drop_column('house', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('size', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('house', sa.Column('deposit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('house', 'price',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('house', 'verified')
    op.drop_column('house', 'rent_per_month')
    op.drop_column('house', 'size_sqft')
    # ### end Alembic commands ###
